=== Klortho/java-xml-tools/test/people.dtd
<!ELEMENT people (person)*>
<!ELEMENT person (name, email, gender, ip-address)>
<!ATTLIST person id CDATA #IMPLIED>
<!ELEMENT name (first, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT ip-address (#PCDATA)>

<!ENTITY snowman "â˜ƒ">

=== Klortho/java-xml-tools/test/needs-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE people SYSTEM "people.dtd">
  
<!-- 
  Test to verify DTDs are used.
  Whatever parser is used to read this file needs to read the DTD, because 
  "Frosty" has the Unicode snowman character as his last name, using an entity
  reference that's defined in the DTD.
-->

<people>

  <person id='1'>
    <name>
      <first>Frosty</first>
      <last>&snowman;</last>
    </name>
    <email>slushy@icy.com</email>
    <gender>Male</gender>
    <ip-address>131.255.94.225</ip-address>
  </person>

  <person id='2'>
    <name>
      <first>Christine</first>
      <last>West</last>
    </name>
    <email>cwest1@theguardian.com</email>
    <gender>Female</gender>
    <ip-address>79.4.55.134</ip-address>
  </person>

  <person id='3'>
    <name>
      <first>Lillian</first>
      <last>Gordon</last>
    </name>
    <email>lgordon2@earthlink.net</email>
    <gender>Female</gender>
    <ip-address>3.132.232.127</ip-address>
  </person>

  <person id='4'>
    <name>
      <first>Deborah</first>
      <last>Edwards</last>
    </name>
    <email>dedwards3@mediafire.com</email>
    <gender>Female</gender>
    <ip-address>137.29.230.224</ip-address>
  </person>

  <person id='5'>
    <name>
      <first>Peter</first>
      <last>Berry</last>
    </name>
    <email>pberry4@vistaprint.com</email>
    <gender>Male</gender>
    <ip-address>53.246.61.190</ip-address>
  </person>

  <person id='6'>
    <name>
      <first>Dennis</first>
      <last>Clark</last>
    </name>
    <email>dclark5@godaddy.com</email>
    <gender>Male</gender>
    <ip-address>163.146.155.14</ip-address>
  </person>

  <person id='7'>
    <name>
      <first>Terry</first>
      <last>Harvey</last>
    </name>
    <email>tharvey6@howstuffworks.com</email>
    <gender>Male</gender>
    <ip-address>16.80.119.68</ip-address>
  </person>

  <person id='8'>
    <name>
      <first>Daniel</first>
      <last>Carter</last>
    </name>
    <email>dcarter7@latimes.com</email>
    <gender>Male</gender>
    <ip-address>245.99.168.90</ip-address>
  </person>

  <person id='9'>
    <name>
      <first>Janice</first>
      <last>Hernandez</last>
    </name>
    <email>jhernandez8@slashdot.org</email>
    <gender>Female</gender>
    <ip-address>93.49.140.250</ip-address>
  </person>

  <person id='10'>
    <name>
      <first>Joyce</first>
      <last>Richards</last>
    </name>
    <email>jrichards9@netvibes.com</email>
    <gender>Female</gender>
    <ip-address>158.52.193.21</ip-address>
  </person>

  <person id='11'>
    <name>
      <first>Melissa</first>
      <last>Hamilton</last>
    </name>
    <email>mhamiltona@networkadvertising.org</email>
    <gender>Female</gender>
    <ip-address>98.7.148.55</ip-address>
  </person>

  <person id='12'>
    <name>
      <first>Eric</first>
      <last>Russell</last>
    </name>
    <email>erussellb@moonfruit.com</email>
    <gender>Male</gender>
    <ip-address>255.140.255.44</ip-address>
  </person>

  <person id='13'>
    <name>
      <first>Donald</first>
      <last>Morris</last>
    </name>
    <email>dmorrisc@cbsnews.com</email>
    <gender>Male</gender>
    <ip-address>15.85.125.120</ip-address>
  </person>

  <person id='14'>
    <name>
      <first>Deborah</first>
      <last>Hawkins</last>
    </name>
    <email>dhawkinsd@npr.org</email>
    <gender>Female</gender>
    <ip-address>231.58.112.119</ip-address>
  </person>

  <person id='15'>
    <name>
      <first>Brandon</first>
      <last>Lopez</last>
    </name>
    <email>blopeze@va.gov</email>
    <gender>Male</gender>
    <ip-address>220.9.55.87</ip-address>
  </person>

  <person id='16'>
    <name>
      <first>Charles</first>
      <last>Howard</last>
    </name>
    <email>chowardf@infoseek.co.jp</email>
    <gender>Male</gender>
    <ip-address>159.17.108.222</ip-address>
  </person>

  <person id='17'>
    <name>
      <first>Benjamin</first>
      <last>Hawkins</last>
    </name>
    <email>bhawkinsg@yellowbook.com</email>
    <gender>Male</gender>
    <ip-address>213.29.255.19</ip-address>
  </person>

  <person id='18'>
    <name>
      <first>Diana</first>
      <last>Riley</last>
    </name>
    <email>drileyh@discuz.net</email>
    <gender>Female</gender>
    <ip-address>39.20.238.21</ip-address>
  </person>

  <person id='19'>
    <name>
      <first>Rachel</first>
      <last>Clark</last>
    </name>
    <email>rclarki@mediafire.com</email>
    <gender>Female</gender>
    <ip-address>234.67.190.68</ip-address>
  </person>

  <person id='20'>
    <name>
      <first>George</first>
      <last>Smith</last>
    </name>
    <email>gsmithj@google.com</email>
    <gender>Male</gender>
    <ip-address>227.93.253.49</ip-address>
  </person>

  <person id='21'>
    <name>
      <first>Jessica</first>
      <last>Rice</last>
    </name>
    <email>jricek@who.int</email>
    <gender>Female</gender>
    <ip-address>200.161.107.192</ip-address>
  </person>

  <person id='22'>
    <name>
      <first>Norma</first>
      <last>Martin</last>
    </name>
    <email>nmartinl@liveinternet.ru</email>
    <gender>Female</gender>
    <ip-address>73.74.203.216</ip-address>
  </person>

  <person id='23'>
    <name>
      <first>Janice</first>
      <last>Sanders</last>
    </name>
    <email>jsandersm@e-recht24.de</email>
    <gender>Female</gender>
    <ip-address>0.29.255.237</ip-address>
  </person>

  <person id='24'>
    <name>
      <first>Kenneth</first>
      <last>Collins</last>
    </name>
    <email>kcollinsn@cbsnews.com</email>
    <gender>Male</gender>
    <ip-address>195.57.222.98</ip-address>
  </person>

  <person id='25'>
    <name>
      <first>Angela</first>
      <last>Reid</last>
    </name>
    <email>areido@nyu.edu</email>
    <gender>Female</gender>
    <ip-address>81.27.23.5</ip-address>
  </person>

  <person id='26'>
    <name>
      <first>Norma</first>
      <last>Romero</last>
    </name>
    <email>nromerop@1und1.de</email>
    <gender>Female</gender>
    <ip-address>230.226.91.107</ip-address>
  </person>

  <person id='27'>
    <name>
      <first>Samuel</first>
      <last>Nichols</last>
    </name>
    <email>snicholsq@dagondesign.com</email>
    <gender>Male</gender>
    <ip-address>12.100.13.184</ip-address>
  </person>

  <person id='28'>
    <name>
      <first>Betty</first>
      <last>Hayes</last>
    </name>
    <email>bhayesr@dyndns.org</email>
    <gender>Female</gender>
    <ip-address>206.67.233.226</ip-address>
  </person>

  <person id='29'>
    <name>
      <first>Wanda</first>
      <last>Hawkins</last>
    </name>
    <email>whawkinss@amazon.co.uk</email>
    <gender>Female</gender>
    <ip-address>69.57.39.116</ip-address>
  </person>

  <person id='30'>
    <name>
      <first>Katherine</first>
      <last>Gonzalez</last>
    </name>
    <email>kgonzalezt@dyndns.org</email>
    <gender>Female</gender>
    <ip-address>242.120.18.97</ip-address>
  </person>

  <person id='31'>
    <name>
      <first>Teresa</first>
      <last>James</last>
    </name>
    <email>tjamesu@google.co.jp</email>
    <gender>Female</gender>
    <ip-address>192.63.102.242</ip-address>
  </person>

  <person id='32'>
    <name>
      <first>Jose</first>
      <last>Butler</last>
    </name>
    <email>jbutlerv@china.com.cn</email>
    <gender>Male</gender>
    <ip-address>215.177.99.133</ip-address>
  </person>

  <person id='33'>
    <name>
      <first>Janice</first>
      <last>Wallace</last>
    </name>
    <email>jwallacew@nbcnews.com</email>
    <gender>Female</gender>
    <ip-address>103.239.139.174</ip-address>
  </person>

  <person id='34'>
    <name>
      <first>Stephanie</first>
      <last>Hansen</last>
    </name>
    <email>shansenx@etsy.com</email>
    <gender>Female</gender>
    <ip-address>180.137.89.249</ip-address>
  </person>

  <person id='35'>
    <name>
      <first>Lisa</first>
      <last>George</last>
    </name>
    <email>lgeorgey@blogger.com</email>
    <gender>Female</gender>
    <ip-address>98.240.157.129</ip-address>
  </person>

  <person id='36'>
    <name>
      <first>Dennis</first>
      <last>Taylor</last>
    </name>
    <email>dtaylorz@phoca.cz</email>
    <gender>Male</gender>
    <ip-address>9.93.63.74</ip-address>
  </person>

  <person id='37'>
    <name>
      <first>Ruby</first>
      <last>Hernandez</last>
    </name>
    <email>rhernandez10@t-online.de</email>
    <gender>Female</gender>
    <ip-address>185.195.222.185</ip-address>
  </person>

  <person id='38'>
    <name>
      <first>Kelly</first>
      <last>Graham</last>
    </name>
    <email>kgraham11@ftc.gov</email>
    <gender>Female</gender>
    <ip-address>76.176.197.73</ip-address>
  </person>

  <person id='39'>
    <name>
      <first>Russell</first>
      <last>Clark</last>
    </name>
    <email>rclark12@china.com.cn</email>
    <gender>Male</gender>
    <ip-address>25.18.170.1</ip-address>
  </person>

  <person id='40'>
    <name>
      <first>Ruth</first>
      <last>Stephens</last>
    </name>
    <email>rstephens13@japanpost.jp</email>
    <gender>Female</gender>
    <ip-address>86.255.252.88</ip-address>
  </person>

  <person id='41'>
    <name>
      <first>Philip</first>
      <last>Lee</last>
    </name>
    <email>plee14@tripod.com</email>
    <gender>Male</gender>
    <ip-address>1.110.157.16</ip-address>
  </person>

  <person id='42'>
    <name>
      <first>Aaron</first>
      <last>Stewart</last>
    </name>
    <email>astewart15@irs.gov</email>
    <gender>Male</gender>
    <ip-address>248.80.179.253</ip-address>
  </person>

  <person id='43'>
    <name>
      <first>Matthew</first>
      <last>Kim</last>
    </name>
    <email>mkim16@ycombinator.com</email>
    <gender>Male</gender>
    <ip-address>107.51.254.47</ip-address>
  </person>

  <person id='44'>
    <name>
      <first>Teresa</first>
      <last>Cooper</last>
    </name>
    <email>tcooper17@alexa.com</email>
    <gender>Female</gender>
    <ip-address>101.57.208.193</ip-address>
  </person>
